### ISSUE TITLE
Open todo list

### ISSUE THREAD

**Issue by aescande** [jrl-umi3218/lexls#2]
This is an issue to keep track and discuss some necessary or possible todos, a priori minors one (but that could be promoted to full issues if needs be).

- [x] [No impact] Fix typos in comments
- [x] [Low impact] Use `Eigen::Ref` in the API, instead of `const dMatrixType &`. This is to avoid the possible creation of a temporary and a copy.
- [ ] [Low impact] Remove `PROBLEM_DATA` from `LexLSE`, and the associated getter. It is marked as `todo REMOVE` in the code and is only there for copying the input data of the decomposition before they are overwritten, seemingly for debugging purpose. Alternatively, we could have a debug flag and make the copy only in this case
- [ ] [Moderate impact][possible] Replace `enum`s with `enum class`es, and simplifiy enum field names accordingly.
- [ ] [possible] Expose internal memory to avoid the copy of `setData`. This might be too dangerous for the expected gain.
- [ ] [possible] Pass a `std::vector` or something similar to describe the level sizes. For now this is done by giving a size and a raw pointer. We could deprecate/remove the actual function in favor of the safer version.
